name: A workflow for my Hello World file
on: push
jobs:
  greet:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Oleksii"
  build:
    name: C# hello world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-b
