name: A workflow for my Hello World file
on: push
jobs:
  greet:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
    - uses: actions/upload-artifact@master
      with:
        name: simple-project
        path: out
